### ISSUE TITLE
Name is not whitelisted

### ISSUE THREAD

**Issue by cjp** [letsencrypt/letsencrypt#1287]
When calling 

```
./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth
```

for domain `0x1.net`, I receive:

```
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Name is not whitelisted
```

despite being invited to the beta via email.

Full log file:
```
2015-11-02 14:52:25,534:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-11-02 14:52:25,536:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-02 14:52:25,536:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151030
2015-11-02 14:52:25,537:DEBUG:letsencrypt.cli:Arguments: ['--agree-dev-preview', '--server', 'https://acme-v01.api.letsencrypt.org/directory']
2015-11-02 14:52:25,537:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-11-02 14:52:25,551:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2015-11-02 14:52:25,873:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache):
Traceback (most recent call last):
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 145, in prepare
    raise errors.NoInstallationError
NoInstallationError
2015-11-02 14:52:25,875:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 50, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2015-11-02 14:52:25,875:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x80aad9650>
Prep: True
2015-11-02 14:52:25,876:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x80aad9650> and installer None
2015-11-02 14:52:25,897:DEBUG:letsencrypt.cli:Picked account: <Account(865a0294cdbf2b88acccc7f8e96b10f4)>
2015-11-02 14:52:25,899:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-11-02 14:52:25,907:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-02 14:52:26,134:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-11-02 14:52:26,138:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Mon, 02 Nov 2015 14:52:26 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 02 Nov 2015 14:52:26 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'E8Z8RfXUKy9Nnho55WbzMV0IxSbynl7nGqSmmU0to5o'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-02 14:52:26,138:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Mon, 02 Nov 2015 14:52:26 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 02 Nov 2015 14:52:26 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'E8Z8RfXUKy9Nnho55WbzMV0IxSbynl7nGqSmmU0to5o'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-02 14:52:26,139:DEBUG:letsencrypt.display.ops:No installer, picking names manually
2015-11-02 14:52:44,249:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0001_key-letsencrypt.pem
2015-11-02 14:52:44,254:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0001_csr-letsencrypt.pem
2015-11-02 14:52:44,257:DEBUG:letsencrypt.client:CSR: CSR(file='/etc/letsencrypt/csr/0001_csr-letsencrypt.pem', data='0\x82\x02|0\x82\x01d\x02\x01\x000\x121\x100\x0e\x06\x03U\x04\x03\x0c\x070x1.net0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xc7\x1c\xcbD~o\xb0HG\xd400\x88e\xd0\x10\xb4;\xcc\x85\x90\xf7H\x89\xf3q\x0e\x0f\xb0T\xae\xf7\x925\x87\xd3y\x1d\xfe\xf7\x9d\x83\xb6\xd9U\xa88\xe2\x15\x07\xe1\x00\x9b\xdc\xbb\xac\x1d\x80LE\x9e\t\xc5q\x16\xd5\xc4\x11\n\xd4>\x1e\x98\xbe\xea9R\x19\xd4~\x1b7g)N\xda\xf1\x14\xe6\xd3c\x0e\x06\xba\xd2\xfc\xeb\x03\x8e\t\x88\xcd\x99\xf4\xb8\xa7\xd8\x94M\xc1S\n\x9e\xc11\x16K\x1c\xd3i\xf1=hb\xdf\x18\xda\xcau\x89\xf3\x8b\x13R\xe2J\xfc3\xd3!7U\x8e\x8b\xbc\x8f!\xb8\xd4\x0e\x87\xc6\xdf\xa9f\x1d\x06\x96\xf9\xf2\xc9i\x84Sj\xd2{g\x8c^\x97\tim\x80O:0\xcd\n\xf3\xe2\xb1\x0b\x1f\xc0D\xbd{\x9f\x83\xf2\x84\xeb\xa6\xdc\xfd\xe4Xg\xbai{\xec\x9b\x16\xe5r\xfa\xca\x9e\xac\x9d\x99<yK\x1d{\xae\x0cdNZ\xaa\x98=E\x1a\xb4\xef\x99V\xd1+\x99B\x9f8S\xc2B\xd6\xaa\x94v \x1f\x87\xf34p\xd1\xe6\xb2\xd3\x02\x03\x01\x00\x01\xa0%0#\x06\t*\x86H\x86\xf7\r\x01\t\x0e1\x160\x140\x12\x06\x03U\x1d\x11\x04\x0b0\t\x82\x070x1.net0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00l\x01\x89\x81_\x0e\x15\x0ef\xa3=%\xa0\tC\x7f\xd4\xe7u\'f\xf1g\x8f$\xa59\x8f\xb1nZ\x97\xdd\'g,\xed]My\xce\xd2v\xe8\x17\xdf\xe8e\xd3)h\xf3eQ)\xa5\r;2\xb6\x97\x96\xb9\x7f\x98Z^0\xd4\xf75o\xb1\x0cv\x86!L\xe8#\xd54\xf3\x15kT\xf7|+\x1d\xcd\x813\xcc\x99\xcc\xa9\xba\xc1\x8aY\xee\xb1\x01sK\xa2\xa6\x03\x18\x87\xda<\x8eP\x08\x83m\\\xd8\x82\xb3\xf2\x1a\x1e\xe9\x1a\x90v\x81u\xca\xb1\x8c\xdb\xe3\xcc{?ub=k\x07\xf2\xa7\x0e\x12\n(\xbat\x8e\x02A\xdeU\xd8f\x8f\xd83\xd3\xe8\xd2v\xac 4\xa1,\xe5\n\x81\xb65\x8bDY\xef\xdc\x9a\x1b\x8bw~&>\xc1<\x91\xf3\x84t\xea\x7f\x1c\xe3\xd8u\x06\xc9xWL\t\x8a\xb4!\xa2\x93$\x004\xacU\xe3\x03\xf9\xec\xca\x01[\xbb\xd2\xe4Y\x17\xdf\xe4\x01`\x12\x84\xbc\x0e|\x9b}\xd4\x11\x13\xca\x9c\x13\xb6\xeb2\x17\xbb\xec\xf8\x90\x9eg\xa7', form='der'), domains: ['0x1.net']
2015-11-02 14:52:44,258:DEBUG:root:Requesting fresh nonce
2015-11-02 14:52:44,258:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2015-11-02 14:52:44,262:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-02 14:52:44,595:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2015-11-02 14:52:44,599:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Mon, 02 Nov 2015 14:52:44 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 02 Nov 2015 14:52:44 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'qmD5nxPaG2tkaZZXEpSCgpt9mciod-FY7UAW19ewuiw'}. Content: ''
2015-11-02 14:52:44,599:DEBUG:acme.client:Storing nonce: '\xaa`\xf9\x9f\x13\xda\x1bkdi\x96W\x12\x94\x82\x82\x9b}\x99\xc8\xa8w\xe1X\xed@\x16\xd7\xd7\xb0\xba,'
2015-11-02 14:52:44,600:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, status=None, combinations=None, challenges=None
2015-11-02 14:52:44,600:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "0x1.net"}, "resource": "new-authz"}
2015-11-02 14:52:44,602:DEBUG:acme.jose.json_util:Omitted empty fields: jwk=None, x5c=(), crit=(), kid=None, jku=None, typ=None, x5u=None, cty=None, x5tS256=None, x5t=None, alg=None
2015-11-02 14:52:44,605:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), nonce=None, kid=None, jku=None, typ=None, x5u=None, cty=None, x5tS256=None, x5t=None
2015-11-02 14:52:44,606:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "pro0UcDLdSxTJ1-WRNMzuZjpxDL2oRbCMCcGSegEADXisAUvwQSHx4E_cOxF9SPGMqhw_AvMkP67TvIb2LzDhtdDB7cSNmA_lWgUhnu7cpSqdcSyzzw_N3sSe_VW3V3GlMw9TkaCl1OHX8UlwHnGPtwfrxXs6686mb3O7JuquqSnjoBMdoTpdGfT8_QJzWeleuPU4V7pESRnMAjzO8tf0HXwsXH5FCBzmFAL9EoZ50jQGSHTl3_Q0n4hRldXTrYcA2o-ao3xUQIhifsHkbu3qy4GFYwfF278rx49xDG1yzNVFAc0GcQ4YMT2ll_y_5AuNzi_hs8QLCe9M96Za31Yzw"}}, "protected": "eyJub25jZSI6ICJxbUQ1bnhQYUcydGthWlpYRXBTQ2dwdDltY2lvZC1GWTdVQVcxOWV3dWl3In0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICIweDEubmV0In0sICJyZXNvdXJjZSI6ICJuZXctYXV0aHoifQ", "signature": "hB5kl8REqBmT-ItG46IUtZrCktvd5SvO_lRVGej1E_uV85-htHgQahSp8CYkjjTMCw3zpoL4c70xQ3TIq80Q8TFWVquNctmaGc684oZtHH6f4F3KIC5_HHsf6gqLNRSJASOtwxQPuIMZ7O6ittyWcBAHWDs4BwAakhX6R67VIuqVMgKcBk-mkqhFA0srvpydXf_Diaty7553cRIhmCQCumP1UYMPchKNLJXG_NDMd01WewWxgMCWVVlG5C8pbv7PU2j3mIFJKM9VGumqbQU_8u31qKiac_OwO-kpdrkQ9LtP9phlMdQ-C6rCeygGRcDCdwZ6kLSEHak0xJ42MnESow"}'}
2015-11-02 14:52:44,608:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-02 14:52:44,888:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 403 101
2015-11-02 14:52:44,894:DEBUG:root:Received <Response [403]>. Headers: {'Content-Length': '101', 'Expires': 'Mon, 02 Nov 2015 14:52:44 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 02 Nov 2015 14:52:44 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'eV_Fgi5y3A_29Ri1RNlXq4jwUuyG_aabhaeCodFGAig'}. Content: '{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Name is not whitelisted"}'
2015-11-02 14:52:44,895:DEBUG:acme.client:Storing nonce: 'y_\xc5\x82.r\xdc\x0f\xf6\xf5\x18\xb5D\xd9W\xab\x88\xf0R\xec\x86\xfd\xa6\x9b\x85\xa7\x82\xa1\xd1F\x02('
2015-11-02 14:52:44,895:DEBUG:acme.client:Received response <Response [403]> (headers: {'Content-Length': '101', 'Expires': 'Mon, 02 Nov 2015 14:52:44 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 02 Nov 2015 14:52:44 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'eV_Fgi5y3A_29Ri1RNlXq4jwUuyG_aabhaeCodFGAig'}): '{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Name is not whitelisted"}'
2015-11-02 14:52:44,899:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/cjp/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1131, in main
    return args.func(args, config, plugins)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 489, in obtaincert
    _auth_from_domains(le_client, config, domains, plugins)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 327, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 212, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 170, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 624, in post
    return self._check_response(response, content_type=content_type)
  File "/home/cjp/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 542, in _check_response
    raise messages.Error.from_json(jobj)
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Name is not whitelisted
```

**Comment by xamnesiax-sx** [comment]
Try with http://0x1.net, or www.0x1.net. Could be a parsing / prefix error ( or feature ), in which case another issue may have to be opened. Worth a try, though.

**Comment by xamnesiax-sx** [comment]
Also, the server seems to be down, that is an issue, as it will attempt to compare the certificate acquired from the server with what you have locally.

**Comment by xamnesiax-sx** [comment]
I think the authentication process also relies on your server being online, as from what I recollect it will attempt to compare the cert received from the server with local certs / keys.

**Comment by rolandshoemaker** [comment]
@xamnesiax-sx is correct about this being a dupe, as `0x1.net` CNAMES to `khujand.0x1.net` Boulder (the backend server) gets confused (ticket for this bug here: letsencrypt/boulder#1048), there is currently a fix in the works for this problem at letsencrypt/boulder#1065.

**Comment by andygabby** [comment]
The error was corrected. It should work now.

**Comment by jackerzhou** [comment]
i have the same error ,Could you tell me how do you solve?

**Comment by ffxsam** [comment]
Same error here too. What does it even mean? If my domain `blah.com` is whitelisted, can I make an SSL for `my.blah.com`? What are the DNS requirements (if any) for `my.blah.com`?

Documentation on this needs a lot of work.

**Comment by akram** [comment]
Hi @kuba @jsha letsencrypt/boulder#1048, letsencrypt/boulder#1065 seems now to be closed resp. merged , and I still face the issue with letsencrypt 0.0.0.dev20151123 .

Is it now required to vendor boulder in letsencrypt head to have this issue fix?

**Comment by bmw** [comment]
Just adding this here as it has been the most common cause of these problems in my experience. Hopefully this helps some of you.

The only names that you are whitelisted for are the fully qualified domain names given in your beta invite. For example, if your beta invite includes only `www.example.com`, you are not whitelisted to get a cert for `subdomain.example.com` or even `example.com`.

If you you'd like a cert for domains outside of those in your beta invite, you need to fill out another beta participation request or wait until public beta on December 3rd.

**Comment by okpatil4u** [comment]
Hi, as letsencrypt is now in public beta, what will be the command to generate certificates now ?
It won't definitely be ./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth .

**Comment by bmw** [comment]
Let's Encrypt is not yet in public beta. That begins on December 3rd, per the announcement [here](https://letsencrypt.org/2015/11/12/public-beta-timing.html).

**Comment by paul-mesnilgrente** [comment]
Hello, today (3rd december),

I runned this command :

```bash
git clone https://github.com/letsencrypt/letsencrypt
cd letsencrypt
./letsencrypt-auto
```

Nice installation, it proposed what domains certificate, I just did yes for all. I gave my gmail email. But the error is : name is not whitelisted.

Should I use a special branch of letsencrypt ?

Thank you very much for your work.

**Comment by BurakDev** [comment]
Public Beta isn't ready yet

https://letsencrypt.status.io/pages/maintenance/55957a99e800baa4470002da/55f7393faca7c180400010fa

**Comment by paul-mesnilgrente** [comment]
okay sorry, I have not found this url, is it possible to know approximatively when it will be ready ? It's still today ? Or in weeks ?

**Comment by BurakDev** [comment]
This night it will be okay :smiley:

**Comment by bmw** [comment]
Since we have now entered public beta, this issue can be closed.
