### ISSUE TITLE
renew: letsencrypt.client:Registering without email!

### ISSUE THREAD

**Issue by ZaneCEO** [letsencrypt/letsencrypt#2748]
I succesfully set up a certificate for https://turbolab.it/ (CentOS 6.7 with Apache 2.2) like this:

````
git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
cd /opt/letsencrypt
./letsencrypt-auto certonly --webroot -w /full/site/path/ -d turbolab.it -d www.turbolab.it
````

I provided my email + agreed to TOS from the *graphic* (blue) UI.

**Now I'm trying to stage the cert renewal but I'm facing issue**. When I try to renew with `./letsencrypt-auto renew --dry-run` I get:

```
[root@skycracker letsencrypt]# ./letsencrypt-auto renew --dry-run
Checking for new version...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt renew --dry-run
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Processing /etc/letsencrypt/renewal/turbolab.it.conf
2016-04-02 13:49:45,115:WARNING:letsencrypt.client:Registering without email!
2016-04-02 13:49:45,910:WARNING:letsencrypt.cli:Attempting to renew cert from /etc/letsencrypt/renewal/turbolab.it.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Please read the Terms of Service at https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf. You must agree in order to register with the ACME server at https://acme-staging.api.letsencrypt.org/directory

(You can set this with the --agree-tos flag). Skipping.
** DRY RUN: simulating 'letsencrypt renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/turbolab.it/fullchain.pem (failure)
** DRY RUN: simulating 'letsencrypt renew' close to cert expiry
**          (The test certificates above have not been saved.)
1 renew failure(s), 0 parse failure(s)
```

The `DeprecationWarning` makes me very uncomfortable, but I understood shouldn't be an issue.

The failure is the real issue here. I understood that the `renew` parameter should fire a renew with the same options used at install-time, so why the failure?

Thanks!

Update: I can confirm that `/etc/letsencrypt/renewal/turbolab.it.conf` holds the correct setting `
email = info@ MY SITE`

**Comment by bmw** [comment]
Thanks for writing such a detailed issue. In short, all problems you are experiencing besides the `DeprecationWarning` are bugs that will be fixed in the next client release in a day or two.

The `DeprecationWarning` is printed by one of our dependencies which was considering dropping support for Python 2.6 sometime in the future. With that said, we've been in contact with them and given how much of our user base is still on Python 2.6, support will not be removed anytime soon.

**Comment by ZaneCEO** [comment]
Excellent, thanks!

I can now confirm that with a `--force-renew` instead of `--dry-run` I was able to renew the certificate.

HTH

**Comment by danpoltawski** [comment]
As far as I can tell, this bug affects the official Ubuntu 16.04 package by following the install instructions exactly.

**Comment by bmw** [comment]
@danpoltawski, yes, this was fixed in the 0.5.0 release but Ubuntu 16.04 is lagging behind. See https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1610030 where we have asked them to upgrade to a more recent package.

**Comment by danpoltawski** [comment]
@bmw It would be great if https://certbot.eff.org/#ubuntuxenial-nginx didn't recommend using those packages if all 16.04 users are just going to hit this issue when you get to 'Automating renewal' step. 😢

**Comment by VickG** [comment]
I got this issue too, and ended up here. 
letsencrypt renew --force-renew 

worked better.

thanks

**Comment by bitinn** [comment]
@bmw for people coming from google search, given Ubuntu 16 still have this old package (`letsencrypt 0.4.1`), the current suggestion is to use `certbot-auto` to get the latest release, right?

Another problem I have seen is while `letsencrypt 0.4.1` says **If you lose your account credentials, you can recover through e-mails sent to [email address].** on certificate creation, I didn't received any email from Let's Encrypt or EFF, I am hoping it's fixed as well.

ref:
- https://certbot.eff.org/docs/install.html

**Comment by bmw** [comment]
I created certbot/website#159 to track the issue of updating renewal instructions for Ubuntu Xenial.
